#! /bin/bash
#
# Usage:
#  build-resource
#
# Builds docker images with the provided configuration values via config.inc.
cfg=config-resource.inc

set -o errexit -o nounset -o pipefail

if [[ "$OSTYPE" == "darwin"* ]]
then
  readonly ExecName=$(greadlink -f "$0")
else
  readonly ExecName=$(readlink --canonicalize "$0")
fi


main()
{
  local baseDir=$(dirname "$ExecName")

  if [ -z "$cfg" ]
  then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  . "$baseDir/$cfg"

  docker build --file "$baseDir"/base/Dockerfile.centos7 --tag irods-docker-deploy-centos7 "$baseDir"

  docker build --file "$baseDir"/base/Dockerfile.ubuntu2004 --tag irods-docker-deploy-ubuntu2004 \
    "$baseDir"

  if ! command -v docker-compose > /dev/null; then
    docker compose --file "$baseDir"/docker-compose-resource.yml --project-name "$ENV_NAME" build
  else
    docker-compose --file "$baseDir"/docker-compose-resource.yml --project-name "$ENV_NAME" build
  fi
}


main "$@"
