---
version: "2.0"

services:
  irods-resource:
    build:
      context: .
      dockerfile: irods-resource/Dockerfile
      args:
        IRODS_CONTROL_PLANE_KEY: "$IRODS_CONTROL_PLANE_KEY"
        IRODS_CONTROL_PLANE_PORT: "$IRODS_CONTROL_PLANE_PORT"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_FIRST_EPHEMERAL_PORT: "$IRODS_FIRST_EPHEMERAL_PORT"
        IRODS_LAST_EPHEMERAL_PORT: "$IRODS_LAST_EPHEMERAL_PORT"
        IRODS_HOST: "$IRODS_HOST"
        IRODS_RESOURCE_HOST: "$IRODS_RESOURCE_HOST"
        IRODS_NEGOTIATION_KEY: "$IRODS_NEGOTIATION_KEY"
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SYSTEM_GROUP: "$IRODS_SYSTEM_GROUP"
        IRODS_SYSTEM_USER: "$IRODS_SYSTEM_USER"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
        IRODS_ZONE_KEY: "$IRODS_ZONE_KEY"
        IRODS_ZONE_PORT: "$IRODS_ZONE_PORT"
        IRODS_ADMIN_USER: "$IRODS_ADMIN_USER"
        IRODS_ADMIN_PASSWORD: "$IRODS_ADMIN_PASSWORD"
        IRODS_MAX_NUM_RE_PROCS: "$IRODS_MAX_NUM_RE_PROCS"
        IRODS_BISQUE_ADMIN_USER: "$IRODS_BISQUE_ADMIN_USER"
    hostname: "$IRODS_RESOURCE_CONF_HOST"
    ports:
      - "1247:1247"
      - "$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT:$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT"
    volumes:
      - "irods_resource_volume:$IRODS_VAULT"
  
volumes:
  irods_resource_volume:
    external: true
  